# Generated by Django 4.2.30 on 2026-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.TextField(blank=True, db_column='Home')),
                ('new_arrival', models.TextField(blank=True, db_column='New Arrival')),
                ('bags', models.TextField(blank=True, db_column='Bags')),
                ('jewellery', models.TextField(blank=True, db_column='Jewellery')),
                ('contact_us', models.TextField(blank=True, db_column='Contact us')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
