# Generated by Django 4.2.30 on 2026-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='bags',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contact_us',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='home',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='jewellery',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='new_arrival',
        ),
        migrations.AddField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='contract',
            name='requirement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
