# Generated by Django 4.2.30 on 2026-06-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contract_bags_remove_contract_contact_us_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '联系表单', 'verbose_name_plural': '联系表单'},
        ),
    ]
